BANCO_DE_DADOS_ENDERECO = "localhost"
BANCO_DE_DADOS_NOME = "unip_tcc"
BANCO_DE_DADOS_USUARIO = "root"
BANCO_DE_DADOS_SENHA = "senha1234"

BUFFER = 4096
SOCKET_PORTA = 9876
SOCKET_ENDERECO = "localhost"

METODO_DE_CLASSIFICACAO = "LN"

TAXA_ATUALIZACAO_ARDUINO = 5

NUMERO_DE_MEDICOES_PARA_DETERMINAR_RISCO = 1

NUMERO_DE_MEDICOES_MINIMAS_DB = 500


print(BUFFER[9])